service: mmeme-lambda

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    
  

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
